### ISSUE TITLE
Adjoint annotation breaks split method

### ISSUE THREAD

**Issue by stephankramer** [firedrakeproject/firedrake#1632]
When running the following code:
```
from firedrake import *
from firedrake_adjoint import *
mesh=UnitSquareMesh(1,1) 
V=FunctionSpace(mesh,"CG",1) 
Z=V*V 
z=Function(V) 
z=Function(Z) 
u,v=z.split() 
u.project(Constant(1.)) 
print(z.dat.data[:])
```
the output is:
```
(array([0., 0., 0., 0.]), array([0., 0., 0., 0.]))
```
instead of the expected:
```
(array([1., 1., 1., 1.]), array([0., 0., 0., 0.]))
```
which is what you get when leaving out the `from firedrake_adjoint import *` line.

The reason seems to be that in the adjoint annotation wrapper for the split method the output from the core split method is wrapped in new Function instances, at which point it looses its connection to the parent `.dat`.

This breaks the Thetis adjoint, as we use the above steps to set initial conditions for velocity and elevation in 2d.

**Comment by nbouziani** [comment]
Yes indeed it is at this point that the connection is lost. Specifying the core split functions as the value argument instead of the main argument when defining the new Function instances enables to keep this connection, that is `Function(u[0].function_space(), u[0])` instead of `Function(u[0])`. 

This has been fixed (cf. https://github.com/firedrakeproject/firedrake/pull/1635) and the associated pyadjoint branch with a new test for that (https://github.com/dolfin-adjoint/pyadjoint/pull/9)

**Comment by wence-** [comment]
@stephankramer can confirm this works?

**Comment by stephankramer** [comment]
Thanks! Works correctly now. Fixes adjoint tests in Thetis

**Comment by stephankramer** [comment]
Sorry, just closed it - but just hit a related issue: it still doesn't work with VectorFunctionSpaces. The following fails:
```
from firedrake import *
from firedrake_adjoint import *
mesh = UnitSquareMesh(1,1)
V = VectorFunctionSpace(mesh, "CG", 1)
u = Function(V)
u.split()
```
I think `num_sub_spaces`(line 50 of firedrake/adjoint/function.py) wants to be something else...does `len(output)` not work in all cases?

**Comment by nbouziani** [comment]
Yes, I think `len(output)` should work in all cases since `num_sub_spaces` is only used to iterate over `output`

**Comment by stephankramer** [comment]
Just realized this doesn't necessarily apply to functions from a VectorFunctionSpace only but also from any other (non-mixed) FunctionSpace - in both cases, the *method* split() doesn't actually do much: it returns a new function using the same .dat, but doesn't actually split anything. The reason I stumbled on this is because split() is called in the .at() method regardless of whether the function is mixed or not. I will put up a fix for firedrake and add a test to pyadjoint.
