### ISSUE TITLE
make alltest, failing on 3 cases.

### ISSUE THREAD

**Issue by twang15** [firedrakeproject/firedrake#680]
Install firedrake with the following setting:
1. OS: ubuntu 15.10, x86_64 bit
2. Reproduce instructions:
curl -O https://raw.githubusercontent.com/firedrakeproject/firedrake/master/scripts/firedrake-install
python firedrake-install
source firedrake/bin/activate
cd firedrake/src/firedrake
make alltest

Failure message attached as a file
[bug-report.txt](https://github.com/firedrakeproject/firedrake/files/102563/bug-report.txt)

**Comment by wence-** [comment]
Thanks, this is another instance of issue #531 (also noticed in #561).

**Comment by twang15** [comment]
Thanks, wence.
It seems it has not been solved.
BTW, I want to use firedrake in my research and thus need to build a developing environment. I have installed firedrake in virtualenv. But, I suppose it is not for development purpose of the firedrake software stack. Could you suggest how to build a developer version of firedrake software stack ? What is the environment you are using ?

Thanks a lot.
I apologize if this is not the place to ask such a question. Could you please kindly let me know where I should post this message for help ?

**Comment by dham** [comment]
The core firedrake developers work do use the install script and develop in the resulting virtualenv.

If what you are planning to do is build finite element solvers using Firedrake, then the setup you have is just fine.

If you think you need to change firedrake itself then you might want to install in developer mode (firedrake-install --developer) so that you are actually running out of your virtualenv's src directory. Of course if you do think you need to extend firedrake itself,  we'd really appreciate knowing what your plans are so we can make sure there are no conflicts with other developments.

**Comment by twang15** [comment]
The project is in a very preliminary phase. It is a research project and should be open-sourced once it is done. Currently, I do not know more details. 
However, the ultimate goal has several folds.
1. Support a new backend
2. Implement more optimizations in COFFEE.
3. Modify other components if necessary, i.e., frontend for new language features, runtime for auto-tuning.

Thus, I need to be able to debug firedrake software stack, see its intermediate representations(IRs), and extend its IRs. These are the reason I consider virtualenv installation may not be sufficient for my purpose. 

I will be glad to discuss more with firedrake community.

**Comment by twang15** [comment]
Moreover, I have to install firedrake on the developing machine which the firedrake-install script does not support. It is centOS 6.7 and I do not have sudo privileges, which means I have to install firedrake one component by another manually.

Currently, I try to install firedrake without the support of firedrake-install script on Ubuntu 15.10 X86_64. Then, I will do this again on centOS 6.7.  I have not succeeded on Ubuntu 15.10(see #681).  This is my plan. Any suggestions ?

**Comment by dham** [comment]
You should still use the install script on centOS. In that case, since you can't install packages with apt, you need to pass --no-package-manager to the install script. This will cause the install script to skip installation of OS packages. The script will print a list of packages which you need to make sure are available (things like compilers and MPI).

As Miklos has already pointed out, running in a virtualenv in no way prevents debugging, or prevents access to the insides of Firedrake. All of the Firedrake core developers use the install script and work in virtualenv when developing Firedrake.

**Comment by twang15** [comment]
1. Doru shared a step-by-step script to me. After modifying it a little bit, I can manually install firedrake on Ubuntu 15.10 X86_64.

2. Installation with firedrake-install script on Ubuntu 15.10 X86_64 is easy.

3. Installation with firedrake-install script on CentOS 6.7. I modified the script at two places:
a) commented out apt-get's try to install system package. This is what you mention "--no-package-manager" option.
b) in firedrake's setup.py, I explicitly added spatialindex's include directory and library path(after I manually install spatialindex, the script does not do this on CentOS. I don't know why). Somehow, on my CentOS machine, without this modification, the firedrake install step fails. The current solution is a work-around. There should be more an elegant solution.

4. Manually install fails on CentOS 6.7.  libpetsc.so has many undefined symbols. I have no idea what happened so far. I may attach the installation script later. But for now, what I have done is following:

git clone -b firedrake https://bitbucket.org/mapdes/petsc.git
git clone -b firedrake https://bitbucket.org/mapdes/petsc4py.git
git clone https://github.com/OP2/PyOP2.git

pip install "Cython>=0.22" decorator "numpy>=1.6" "mpi4py>=1.3.1"
pip install  flake8

#install petsc
cd petsc
./configure --download-ctetgen --download-triangle --download-chaco --download-hdf5 --download-fblaslapack --with-shared-libraries=1
export PETSC_DIR="$PWD"
export PETSC_ARCH="arch-linux2-c-debug"

make PETSC_DIR="$PWD" PETSC_ARCH="arch-linux2-c-debug" all
export PYTHONPATH="$PWD:$PWD/$PETSC_ARCH/lib:$PYTHONPATH"
export LD_LIBRARY_PATH=$PWD/$PETSC_ARCH/lib:$LD_LIBRARY_PATH

#install petsc4py
cd ../petsc4py
python setup.py install --user

# Install FIAT
# SWIG install
# Install UFL
# Install FFC"

#Install PyOP2
cd ../PyOP2
python setup.py build_ext -i
pip install  pytest
pip install  pytest-xdist
export PYTHONPATH="$PWD:$PYTHONPATH"
pip install --user networkx
make test
###ERROR occurs here: many undefined symbols in various .so library######
###I have no idea what is going on ###########

**Comment by dham** [comment]
OK, manual install is not a supported option, so we're not going to attempt to fix 1 or 4. I'm glad 2 works, because that's a tested option.

We are very interested in install script fails. 3.a. is not a bug - as you point out, the right thing to do is to pass --no-package manager.

3.b. Is interesting. Could you please post the change you made to make 3.b work and we can see how to make things so that it's not necessary to modify the script.

**Comment by twang15** [comment]
The error message is as following:
firedrake/spatialindex.cpp:259:39: error: spatialindex/SpatialIndex.h: No such file or directory

So I guess it is because the library spatialindex is not installed properly.
Then I try several methods:
a. brew install spatialindex. brew says the installation is successful and I can see the include header and library installed, these paths are also in PKG_CONFIG and LD_LIBARRY_PATH.

Result: firedrake setup.py still cannot find spatialindex. Same error message.

b. Manually install spatialindex.
wget http://download.osgeo.org/libspatialindex/spatialindex-src-1.8.5.tar.gz
tar xvf spatialindex-src-1.8.5.tar.gz
cd spatialindex-src-1.8.5
./configure --prefix=/home1/03915/taoncsu/tools/python
make
make install

Then, I modified firedrake/src/firedrake/setup.py
#after line 63
include_dirs_extra = ["/home1/03915/taoncsu/tools/python/include"]
include_dirs += include_dirs_extra

# line 92
# then in Extension('firedrake.spatialindex' ....
#replace line "include_dirs=[np.get_include()]," with
# include_dirs=include_dirs,

Then run:
cd $HOME/firedrake/src/
source ../bin/activate
../bin/pip install --no-deps --ignore-installed firedrake/

Result: success build firedrake.

Any idea for an elegant solution ?

**Comment by twang15** [comment]
Another solution is
export LIBRARY_PATH=/home1/03915/taoncsu/tools/python/include:$LIBRARY_PATH

**Comment by dham** [comment]
I think we should add libspatialindex to the install script so this Just Happens.

Currently all the other things that we expect the OS to provide are pretty generic. Libspatialindex is rather specialised.

**Comment by twang15** [comment]
Yes, that may be better.
Besides, --download-fblaslapack is also needed on CentOS 6.7. I failed to install it with brew. It seems, by default, this option should be there.

**Comment by dham** [comment]
Blas and Lapack are a bit different. The reference Blas implementation that PETSc will download may well not be what users want, so we shouldn't do that automatically. However, you can already specify --download-fblaslapack in PETSC_CONFIGURE_OPTIONS and firedrake-install will honour that. So I think that option is already fixed.

**Comment by twang15** [comment]
I see there is update in the installation script. But, it still fails on CentOS 6.7.
The problem is exactly the same, so I tried the solution I developed before 

> Then, I modified firedrake/src/firedrake/setup.py
#after line 63
include_dirs_extra = ["/home1/03915/taoncsu/tools/python/include"]
include_dirs += include_dirs_extra

#at line 92
#then in Extension('firedrake.spatialindex' ....
#replace line "include_dirs=[np.get_include()]," with "include_dirs=include_dirs,"

But, this time the failing command is different, which is
/work/03915/taoncsu/firedrake.impi/firedrake/bin/python -c "import setuptools, tokenize;__file__='/work/03915/taoncsu/firedrake.impi/firedrake/src/firedrake/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps

I need cd to firedrake/src/firedrake to run this command successfully.

This is the output:
_Adding firedrake unknown to easy-install.pth file
Installing firedrake-clean script to /work/03915/taoncsu/firedrake.impi/firedrake/bin
Installing firedrake-install script to /work/03915/taoncsu/firedrake.impi/firedrake/bin

Installed /work/03915/taoncsu/firedrake.impi/firedrake/src/firedrake_

My question are:   
1. Is this the very last command that I should run ? Are there any other steps to do ?
2. Does it mean the installation is successful ?
3. How can I update firedrake ?   In the script firedrake-install, I found "To upgrade firedrake, run firedrake/bin/firedrake-update". However, there is no such firedrake-update installed there. Is there anything wrong ?
4. After I develop code in firedrake module, how can I build it?  and How can I debug it ?  Are there any method or tools to debug firedrake ?

**Comment by miklos1** [comment]
1* and 2* Best way to make sure that the installation was successful is to run the test suite. Run can do that by typing `make alltest` in the firedrake source directory, which will run flake8 for linting, and then runs `py.test tests`.


3* Not sure about what you did and why you have no firedrake-update. Most of the time it's enough the pull the repositories for an upgrade. Some packages are not pure Python (PETSc, petsc4py, PyOP2 and Firedrake) they need rebuilding when they change. Occasionally, however, there are changes in dependencies etc. which are more difficult to do manually, but the update script takes care of them


4* If you change some of the Cython files (*.pyx), you need to rebuild them using `make` in the firedrake directory. Otherwise Python needs no building, it's an interpreted language. The standard Python, Cython and C development and debugging tools shall be satisfactory. Have IPython, ipdb, flake8, gdb and valgrind. The latter two is only needed when you machinate code generation or Cython files, and the failure / bug happens in "unsafe" code. It's also good to know that you can lunch ipython and ipdb from the python program, like this:

    import ipdb; ipdb.set_trace()

or:

    import IPython; IPython.embed()

**Comment by wence-** [comment]
I believe this issue was fixed by a recent change in PyOP2.  At least, I can no longer reproduce it.
